# Generated by Django 4.1 on 2022-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
    ]
